### ISSUE TITLE
incorrect error handling of erroneous command line arguments

### ISSUE THREAD

**Issue by jkzilla** [treddeni/ripple-bot#2]
program crashes instead of validating command line arguments and printing out command line usage help

**Comment by jkzilla** [comment]
$ node app.js
module.js:339
    throw err;
    ^

Error: Cannot find module '../configs/undefined'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/johanna/src/ripple-bot/ripple-bot/src/logger.js:2:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
$

**Comment by treddeni** [comment]
I added a usage/help comment to the command line.  Unfortunately, it looks like they changed the way ripple-lib works, so now ripple-bot is broken.  I added this issue for it: https://github.com/treddeni/ripple-bot/issues/3
